logo: images/logo.png
title: MQTT Connector
email: juandesimoni@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  mqtt connector is an MQTT 5.0 and MQTT 3.1.1 compatible and feature-rich 
  high-performance mulesoft connector.
baseurl: "/mqtt-connector" # the subpath of your site, e.g. /blog
url: "https://www.juan.desi" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juandesi
github_username:  juandesi

# Build settings
remote_theme: pmarsceill/just-the-docs@654da0a
theme: "just-the-docs"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-redirect-from

search_enabled: true
  
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
